#!/usr/bin/env bash
# Buildkite integration-test step for qdb-nats-connector.
# Invoked by .buildkite/steps/_build.yml after start-services.sh,
# 20.build.sh, and 30.test-unit.sh.
#
# Integration tests live under test/integration/ and are guarded by
# //go:build integration, so they are excluded from 30.test-unit.sh
# (which omits -tags=integration) and run only here.
#
# Services: qdbd (insecure 127.0.0.1:2836, secure 127.0.0.1:2838) is
# already provisioned by scripts/tests/setup/start-services.sh earlier
# in the _build.yml chain. This script must NOT start services and must
# NOT set RUN_SEGFAULT_TEST (TestComputeFieldSegfault stays opt-in).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$(dirname "${SCRIPT_DIR}")")"

# Source shared CGO and Go-toolchain env helpers.
source "${SCRIPT_DIR}/00.common.sh"

# Required when the docker plugin propagates the host UID into the
# container: git refuses to operate on a workspace owned by a different
# user without this. Mirrors scripts/cicd/30.test-unit.sh.
git config --global --add safe.directory '*'

cd "${BASE_DIR}"

# --- env setup ---

if [[ ! -d "qdb/lib" || ! -d "qdb/include" ]]; then
    echo "ERROR: expected qdb/lib and qdb/include to be present." >&2
    echo "The qdb-c-api fetch is currently user-managed; run it before 40.test-integration.sh." >&2
    exit 1
fi

cicd_setup_qdb_env
cicd_setup_go_toolchain

# --- test ---

GO_EXTRA_FLAGS=()

echo "Running integration tests (-tags=integration)"
# -buildvcs=false: same rhel7 uid/no-passwd VCS-stamping failure as
# 20.build.sh / 30.test-unit.sh.
if [[ "$(uname)" == MINGW* ]]; then
    # Integration tests invoke test binaries generated by `go test`, currently PATH is in unix style.
    # For the test binaries to resolve the qdb and MinGW DLLs at startup, we need to convert PATH to
    # Windows format and exec the test binaries in that environment.
    # The wrapper script windows-go-test-exec.sh does exactly that, and is invoked via `-exec` here.
    # See that script for details.
    GO_EXTRA_FLAGS+=(-exec "bash ${SCRIPT_DIR}/windows-go-test-exec.sh")
fi

"${GO}" test "${GO_EXTRA_FLAGS[@]+"${GO_EXTRA_FLAGS[@]}"}" -buildvcs=false -tags=integration -race ./test/integration/...
