label: ":go: test-unit ({slug})"
key: test-unit-{slug}

commands:
  - bash scripts/cicd/30.test-unit.sh

plugins:
  - bureau14/qdb-artifacts#master:
      download:
        project_id: "quasardb"
        output-dir: "qdb"
        extract: true
        clean: true
        files:
          - "*-c-api.tar.zst!*"
          - "*-server.tar.zst!*"
          - "*-utils.tar.zst!*"
      promote: {}

timeout_in_minutes: 30

agents:
  queue: "default-{queue}"
