name: Lint

on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python3 -m pip install -r scripts/github_actions/requirements.txt

      - name: Check Go formatting
        id: go_fmt
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]
          then
            echo "::error::Code is not properly formatted"
            gofmt -d .
            exit 1
          fi

      - name: Run go vet
        id: go_vet
        run: go vet ./...

      - name: Run staticcheck
        id: staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Run ineffassign
        id: ineffassign
        run: |
          go install github.com/gordonklaus/ineffassign@latest
          ineffassign ./...

      - name: Run golangci-lint
        id: golangci_lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Send Slack notification
        if: ${{ !cancelled() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_CHANNEL: ${{ vars.SLACK_BOT_CHANNEL }}
        run: |
          python scripts/github_actions/post_lint.py \
            go_fmt=${{ steps.go_fmt.outcome }} \
            go_vet=${{ steps.go_vet.outcome }} \
            staticcheck=${{ steps.staticcheck.outcome }} \
            ineffassign=${{ steps.ineffassign.outcome }} \
            golangci_lint=${{ steps.golangci_lint.outcome }}
